name: Radiotap
markdown: kramdown
baseurl: /radiotap.github.io
defaults:
 -
  scope:
     path: "" # everything
  values:
    layout: "default"
#gems:
#  - jekyll-redirect-from

theme: jekyll-theme-slate